### ISSUE TITLE
关于 checkbox 的多选

### ISSUE THREAD

**Issue by anziguoer** [why520crazy/angular-w5c-validator#37]
<h4>有个这样的多选 checkbox</h4>
    <div class="form-group">
               <label class="col-sm-2 control-label">全国校区</label>
               <div class="col-sm-10">
                   <label class="checkbox-inline" ng-repeat="campus in vm.campuses">
                       <input type="checkbox" name="campuses" ng-model="entity.campuses[campus.campusId]" ng-true-value="{{campus.campusId}}">{{campus.campusName}} 
                  </label>             
               </div>
           </div>

campuses 的格式是这样的：
<code>
[
  {
    "campusId" : 1,
    "campusName" : "北京校区"
  },
  {
    "campusId" : 2,
    "campusName" : "上海校区"
  },
  {
    "campusId" : 3,
    "campusName" : "武汉校区"
  },
  {
    "campusId" : 4,
    "campusName" : "南京校区"
  },
  {
    "campusId" : 5,
    "campusName" : "成都校区"
  }
]
</code>
<h4>这样绑定：</h4>
 vm.campuses = campuses;

<h4>checkbox 在点击的时候报错：</h4>
<code>
TypeError: Cannot set property '1' of undefined
    at extend.assign (http://localhost/hxsdWebFramework/20151117/script/angular.js:9038:26)
    at $setViewValue (http://localhost/hxsdWebFramework/20151117/script/angular.js:15404:7)
    at http://localhost/hxsdWebFramework/20151117/script/angular.js:14928:12
    at Scope.$eval (http://localhost/hxsdWebFramework/20151117/script/angular.js:10699:28)
    at Scope.$apply (http://localhost/hxsdWebFramework/20151117/script/angular.js:10796:23)
    at HTMLInputElement.<anonymous> (http://localhost/hxsdWebFramework/20151117/script/angular.js:14927:11)
    at http://localhost/hxsdWebFramework/20151117/script/angular.js:2331:10
    at Array.forEach (native)
    at forEach (http://localhost/hxsdWebFramework/20151117/script/angular.js:213:11)
    at HTMLInputElement.eventHandler (http://localhost/hxsdWebFramework/20151117/script/angular.js:2330:5)
</code>
<h3>
请问我改如何实现 checkbox 的多选呢？</h3>

**Comment by why520crazy** [comment]
关于动态checkbox，参考 http://jsfiddle.net/bmleite/PQvQ2/ 或者 http://plnkr.co/edit/ALHQtkjiUDzZVtTfLIOR?p=preview

**Comment by anziguoer** [comment]
嗯， 不过我用的是 angular-w5c-validator，按我上面的写法是报错的！

**Comment by why520crazy** [comment]
你这个报错和  angular-w5c-validator 没有任何关系，你不用  angular-w5c-validator 组件试试看是否也还报错
